[Qt][C++][WIP] Oauth2 Authorization Code Flow support.
OpenAPITools/openapi-generator pull request #10183
Opened 2021-08-18 11:56 UTC by basyskom-dege

This PR will enable OAuth2 Support for the Authorization Code Flow. The oauth-class will provide a reply server based on the  QTcpserver module. This is a followup PR from #8831. I took some input from @etherealjoy `s comment in the old PR. 
But there are some steps unclear:

Where should we store the information for the request? We need the state, ClientId and ClientSecret etc. This [Comment](https://github.com/basyskom-dege/openapi-generator/blob/2f6c9671b08e834058254ee288be9a8b1556af1d/modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache#L747) refers to the [Specification](https://swagger.io/docs/specification/authentication/oauth2/) that states we should use the tools we like to provide those variables. Do you have something in mind here? My take would be a config file in some way. 

Another problem might be the fact that the oauth flow can only be used in a `QtGuiApplication` since it uses the `QDesktopServices::openUrl()` function to open the oauth pop-up window. 

Because of those questions, i marked it as WIP. Any feedback or input would be highly appreciated!

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

PING @wing328 @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @MartinDelille (2018/03) @muttleyxd (2019/08)

2021-08-29 10:20 UTC, MartinDelille requested changes

2021-08-29 10:20 UTC, MartinDelille commented on modules/openapi-generator/src/main/resources/cpp-qt-client/Project.mustache
> +    $${PWD}/oauth.h
Why this file don't use `{{prefix}}` ?

2021-09-06 09:08 UTC, basyskom-dege commented on modules/openapi-generator/src/main/resources/cpp-qt-client/Project.mustache
> +    $${PWD}/oauth.h
Missed that. Fixed now

2021-10-30 08:06 UTC, MartinDelille approved these changes
I'm not an expert in Oauth2 authorization management so I cannot judge but at least I can say that this PR doesn't break anything.

2021-11-01 16:16 UTC, basyskom-dege commented
> I'm not an expert in Oauth2 authorization management so I cannot judge but at least I can say that this PR doesn't break anything.

Im not an expert as well but maybe @etherealjoy has some more knowledge to do a review.

For testing i used multiple "test" server. For the Implicit and Authorization Code Flows, i used the [Google Oauth2 API](https://developers.google.com/identity/protocols/oauth2). You have to create an Web-App, set the redirect url to `http://127.0.0.1:9999` (the reply server is running on localhost with port 9999). Google provides all infos (client_id, secret) that you have to set in the callback of an API call:
`setVariables(tokenUrl , scopeStr ,"clientId", "clientSecret", ...);`

For the client credential flow, I used tools from [HERE](https://oauth.tools/). They also provide the other flows but you cant set the redirect url to localhost...

The password flow has to be tested "manually" because it is deprecated and considered unsafe for obvious reasons. But since its in OpenAPI, I added it aswell. I used a Node.js server with router from Express package. I just added a route and logged the client_id and answered with a fixed token since its just for testing:

```
var express = require('express');
var router = express.Router();
[...]
router.post('/auth',function (req, res, next) {
  var id = req.query.client_id;
  console.log("Client ID: ",id);
  res.setHeader('Content-Type', 'application/json');
  res.json({   token_type: "Bearer",
                    expires_in: 86400,
                    access_token: "E3ySJQtKPFKkzgIin7oNnJ8-39lTKeEI0NDC7apzqfPSIBErHJb8tYJqq5niZQtj8CHZG9u1",
                    scope: "read"});
});

```
I used the following securitySchemes in the input file:

```
  securitySchemes:
      clientCred:
        type: oauth2
        flows:
            clientCredentials:
              tokenUrl: https://login-demo.curity.io/oauth/v2/oauth-token
              scopes:
                'read': read your pet
      implicit:
        type: oauth2
        flows:
            implicit:
              authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
              scopes:
                'https://www.googleapis.com/auth/drive.metadata.readonly': read your pet
      password:
        type: oauth2
        flows:
          password:
            tokenUrl: http://localhost:3000/order/auth
            scopes:
                'read': read your pet
      authCode:
        type: oauth2
        flows:
          authorizationCode:
            authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
            tokenUrl: https://oauth2.googleapis.com/token
            scopes:
                'https://www.googleapis.com/auth/drive.metadata.readonly': read your pet
```

2021-11-02 08:50 UTC, MartinDelille approved these changes

2021-11-14 15:16 UTC, merged

2021-11-15 10:12 UTC, wing328 commented
@basyskom-dege looks like this breaks the build:
```
-- Build files have been written to: /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build
/usr/local/cmake-3.12.4/bin/cmake -H/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt -B/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/cmake-3.12.4/bin/cmake -E cmake_progress_start /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/CMakeFiles /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build'
make -f client/CMakeFiles/client_autogen.dir/build.make client/CMakeFiles/client_autogen.dir/depend
make[2]: Entering directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build'
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build && /usr/local/cmake-3.12.4/bin/cmake -E cmake_depends "Unix Makefiles" /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client/CMakeFiles/client_autogen.dir/DependInfo.cmake --color=
Scanning dependencies of target client_autogen
make[2]: Leaving directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build'
make -f client/CMakeFiles/client_autogen.dir/build.make client/CMakeFiles/client_autogen.dir/build
make[2]: Entering directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build'
[  4%] Automatic MOC for target client
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client && /usr/local/cmake-3.12.4/bin/cmake -E cmake_autogen /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client/CMakeFiles/client_autogen.dir/AutogenInfo.cmake ""
make[2]: Leaving directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build'
[  4%] Built target client_autogen
make -f client/CMakeFiles/client.dir/build.make client/CMakeFiles/client.dir/depend
make[2]: Entering directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build'
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build && /usr/local/cmake-3.12.4/bin/cmake -E cmake_depends "Unix Makefiles" /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client/CMakeFiles/client.dir/DependInfo.cmake --color=
Scanning dependencies of target client
make[2]: Leaving directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build'
make -f client/CMakeFiles/client.dir/build.make client/CMakeFiles/client.dir/build
make[2]: Entering directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build'
[  9%] Building CXX object client/CMakeFiles/client.dir/PFXApiResponse.cpp.o
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client/client_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fPIC -Wall -Wno-unused-variable -fPIC -Wall -Wno-unused-variable   -fPIC -std=c++14 -o CMakeFiles/client.dir/PFXApiResponse.cpp.o -c /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client/PFXApiResponse.cpp
[ 13%] Building CXX object client/CMakeFiles/client.dir/PFXCategory.cpp.o
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client/client_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fPIC -Wall -Wno-unused-variable -fPIC -Wall -Wno-unused-variable   -fPIC -std=c++14 -o CMakeFiles/client.dir/PFXCategory.cpp.o -c /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client/PFXCategory.cpp
[ 18%] Building CXX object client/CMakeFiles/client.dir/PFXOrder.cpp.o
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client/client_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fPIC -Wall -Wno-unused-variable -fPIC -Wall -Wno-unused-variable   -fPIC -std=c++14 -o CMakeFiles/client.dir/PFXOrder.cpp.o -c /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client/PFXOrder.cpp
[ 22%] Building CXX object client/CMakeFiles/client.dir/PFXPet.cpp.o
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client/client_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fPIC -Wall -Wno-unused-variable -fPIC -Wall -Wno-unused-variable   -fPIC -std=c++14 -o CMakeFiles/client.dir/PFXPet.cpp.o -c /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/client/PFXPet.cpp
[ 27%] Building CXX object client/CMakeFiles/client.dir/PFXTag.cpp.o
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/sa [...]

2021-11-15 13:30 UTC, basyskom-dege commented
Yes, i forgot to add the QT5Gui Package for Cmake (this is needed to open the authURL in the browser).
I also forgot to update the CMakeLists.txt that caused namespace issues.

Should be fixed now. Integration-test works on my machine. I pushed it to my Branch. Should i open a new PR?

2021-11-20 01:06 UTC, wing328 commented
Yes please open a new PR

2021-11-22 10:20 UTC, basyskom-dege commented
> Yes please open a new PR

 Done -> #10921