Kmc026 project
OpenAPITools/openapi-generator pull request #11123
Opened 2021-12-14 19:46 UTC by kmc026

This commit is attempting to fix the issue #6675.
According to the issue, when specific regex patterns are used in the OpenAPI declaration yaml files, using Python will cause a formatting issue where a backslash \ will be added after an opening bracket [ and cause a double backslash \ in the outputted sample Default API file. The validation for the sample Default API will then fail.

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

2021-12-29 03:36 UTC, wing328 commented
@kmc026 thanks for the PR.

cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)

2021-12-30 21:08 UTC, spacether commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonLegacyClientCodegen.java
> +    public String fixRegexBackSlashError(String pattern, Map<String, Object> vendorExtensions) {
How about setVendorExtensionRegex?
Yes it fixes a bug but more importantly it sets the vendor extension regex

2021-12-30 21:13 UTC, spacether commented on modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonLegacyClientCodegenTest.java
> +        // Issue #6675: Transform issue_6675_problematic_pattern_1 from issue_1517.yaml
How about testing that the x-regex vendor extension contains the right value?
hat's what our templates need.

2021-12-30 21:24 UTC, spacether requested changes
Hi there. Thank you for your PR.
In addition to addressing the comments that I left, can you also remove you samples/ additions? If you want to add testing, you can add a sample spec file like we have in our java layer testing in PythonLegacyClientCodegenTest. If you want to see the samples updated, you can add a new regex in the current spec file that our python sample uses at: `bin/configs/python-legacy.yaml` and if you want to add a test in python you can add it in the `samples/openapi3/client/petstore/python-legacy/tests_manual`

2022-11-04 10:44 UTC, spacether commented
@kmc026 can you try the 6.2.1 release?
There was a fix for regex handling in that python client. If that works, can this PR be closed?

2023-01-07 04:20 UTC, spacether commented
It looks like this is no longer needed as it was fixed in https://github.com/OpenAPITools/openapi-generator/pull/10920

2023-01-07 04:20 UTC, closed without merging