Enums comparator with ignore case
OpenAPITools/openapi-generator pull request #12881
Opened 2022-07-15 11:02 UTC by wtrocki

- fix: add value matching with ignore case syntax
- chore: regenerated samples apps

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

2022-07-15 11:07 UTC, wtrocki commented
Working on issue on my end with generating samples.

2022-07-15 11:11 UTC, wtrocki commented
Looks like python examples on main require specific python version and have been failing on my end

2022-07-15 13:45 UTC, borsch commented on modules/openapi-generator/src/main/resources/Java/modelEnum.mustache
> +      if (b.value.{{^isString}}equals{{/isString}}{{#isString}}equalsIgnoreCase{{/isString}}(value)) {
as for me you should compare enum's constant name. so should be something like this

`if (b.value.equals(value){{#isString}} || b.name().equals(value){{/isString}}) {`

2023-04-14 06:11 UTC, rodrigoma3 commented
@wtrocki I'm in need of this fix, could you finalize and merge? Or authorize me to continue from here on your branch?

2023-04-14 09:32 UTC, wtrocki commented
@wing328 Would you be willing to accept that PR - happy to rebase.

2023-04-17 19:14 UTC, rodrigoma3 commented
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09)
Can we go ahead with this fix?

2023-04-17 21:25 UTC, wtrocki commented
@rodrigoma3 feel free to open new PR based off my changes

2023-04-18 14:02 UTC, borsch commented
@wtrocki can you rebase this PR?

2023-04-18 16:22 UTC, borsch requested changes

2023-04-18 16:22 UTC, borsch commented on samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
> +@.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
this is weird

2023-04-18 16:22 UTC, borsch commented on samples/client/echo_api/java/apache-httpclient/.openapi-generator/VERSION
> +6.3.0-SNAPSHOT
pull latest master

2023-04-18 16:26 UTC, wtrocki commented on samples/client/echo_api/java/apache-httpclient/.openapi-generator/VERSION
> +6.3.0-SNAPSHOT
I though I did. Will do now.

2023-04-28 14:28 UTC, borsch commented
closing since since similar changes were merged in https://github.com/OpenAPITools/openapi-generator/pull/15273

2023-04-28 14:28 UTC, closed without merging