Update beanValidationCore.mustache
OpenAPITools/openapi-generator pull request #13631
Opened 2022-10-07 11:04 UTC by matheustf

Update to use x-pattern-message for message customization

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

2022-10-07 11:09 UTC, matheustf commented
Update to use x-pattern-message for message customization

2023-04-12 18:13 UTC, rodrigoma3 commented
@cachescrubber @welshm @MelleD @borsch @Zomzog @atextor @manedev79 @javisst @banlevente 
Can you merge pull request please?

2023-04-12 20:52 UTC, rodrigoma3 commented
@wing328 ping

2023-04-12 21:38 UTC, welshm commented
It would be good to add tests for this if possible - I don't see any issues with teh change though, but might be good to document the usage of `x-pattern-message` - https://openapi-generator.tech/docs/generators/spring#supported-vendor-extensions

2023-04-13 18:57 UTC, matheustf commented
@cachescrubber @welshm @MelleD @borsch @Zomzog @atextor @manedev79 @javisst @banlevente
We update with the documentation. Can you merge pull request please?

2023-04-14 09:28 UTC, borsch commented on docs/generators/spring.md
> +|x-pattern-message| Add this property whenever you need to customize the invalidation error message for the regex pattern of a variable|FIELD|
we don't add this manually. Add this to https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/VendorExtension.java + add it as supported extension to https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L1241


once all this done you would need to re-generated docs using
`mvn clean && ./bin/utils/export_docs_generators.sh`

2023-04-14 09:28 UTC, borsch requested changes
Please update docs accordingly

2023-04-20 17:32 UTC, rodrigoma3 commented
@borsch 
done

2023-04-21 07:07 UTC, borsch approved these changes

2023-04-21 07:08 UTC, merged