typescript-nestjs: queryParameters need to be a URLSearchParameter in order to work
OpenAPITools/openapi-generator pull request #13638
Opened 2022-10-07 14:55 UTC by danielbrammertz

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

2022-10-18 14:41 UTC, macjohnny requested changes
thanks for your contribution

2022-10-18 14:41 UTC, macjohnny commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
> +            queryParameters.append('{{baseName}}',{{paramName}}.toString());
```suggestion
            queryParameters.append('{{baseName}}', String({{paramName}}));
```

2022-11-28 22:53 UTC, joelongstreet commented
@danielbrammertz - I'm having this same problem. Looks like this pull request has been stale for a few weeks. Mind if I get it across the finish line?

2022-11-28 22:57 UTC, danielbrammertz commented
I would very much appreciate it. Thanks a lot!

Am 28.11.2022 um 23:53 schrieb Joe Longstreet ***@***.***>:

﻿

@danielbrammertz<https://github.com/danielbrammertz> - I'm having this same problem. Looks like this pull request has been stale for a few weeks. Mind if I get it across the finish line?

—
Reply to this email directly, view it on GitHub<https://github.com/OpenAPITools/openapi-generator/pull/13638#issuecomment-1329858076>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYTYXK4F73PZX626TYHQEITWKUZVPANCNFSM6AAAAAAQ7VNEYM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-29 00:34 UTC, joelongstreet commented
@danielbrammertz - Ok, sounds good. Just opened a pull request here: https://github.com/OpenAPITools/openapi-generator/pull/14139. 

@wing328 - Mind if we move the conversation over to the updated pull request and close this one?

2022-11-29 08:42 UTC, closed without merging