Remove @InputFile, use a simple @Input #13726
OpenAPITools/openapi-generator pull request #13727
Opened 2022-10-18 10:32 UTC by hdani9307

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

2022-10-18 13:26 UTC, erichaagdev commented
👋 @hdani9307 could you briefly explain why you would like to make this change? What issue are you experiencing that you are trying to address with these changes?

2022-10-18 13:43 UTC, hdani9307 commented
Hi @erichaagdev

I wanted to generate the API from an URL like `https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator-gradle-plugin/src/test/resources/specs/petstore-v3.0.yaml` in my project, but because of the `@InputFile` annotation in the GenerateTask, it is only accepting file urls, however the http url inputspec is supported by the generator.

2022-10-18 16:12 UTC, erichaagdev commented
@hdani9307 thanks for the explanation. Annotating file inputs with `@InputFile` is required to properly support incremental build functionality (e.g. `UP-TO-DATE`). You can read [the Incremental Build section of the Gradle documentation](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks) to learn more.

Introducing these changes as is would cause a regression for functionality that was previously added by #4492, #6472, and #6716.

With that being said, you may still be able to implement the functionality you want without causing a regression or impacting backwards compatibility. What I recommend is to leave `inputSpec` as is and instead add a _new_ property (e.g. `remoteInputSpec`) which can be annotated with `@Input` and used only if `inputSpec` is not defined. 

Since Gradle has no way to know if the contents of the remote spec have changed, you would need to conditionally disable caching if the new property is in-use. Proper incremental building would not be supported, but to generate a new set of classes caused by changes to the remote specification you can always run a `clean`. 

Another option is to conditionally register an additional non-cacheable/non-incremental task which would first download the remote specification as a pre-requisite step to the generate task. This would allow the generate task to still fully support build caching and incremental building.

2022-10-20 13:32 UTC, hdani9307 commented
@erichaagdev If I create a new `remoteInputSpec` property, I will have to make the `inputSpec` parameter optional. Currently it is a required property. Would it cause any regression issue?

2022-10-20 17:48 UTC, erichaagdev commented
@hdani9307 I don't believe marking a previously required property with `@Optional` would break any backwards compatibility. Removing the `@Optional` annotation from a property and making it required would, but that's not what you would be doing. 

I'd also like to propose an alternative solution - one which only requires you to modify your own build scripts. You could leverage [the `gradle-download-task` plugin](https://github.com/michel-kraemer/gradle-download-task) and add a task downloading the remote OpenAPI specification. You would then use the location of the downloaded spec file as the value for `inputSpec`. 

Here is a sample showing how that could be done: https://github.com/erichaagdev/gradle-samples/blob/main/remote-openapi-spec/build.gradle.kts

2022-10-27 09:14 UTC, hdani9307 commented
@erichaagdev I have added the new `remoteInputSpec` property. 

Thank you for your alternative suggestion, we are already using the same plugin as a workaround. It works well, I just wanted to fix this bug in the lib.

2022-10-29 13:22 UTC, erichaagdev requested changes

2022-10-29 13:22 UTC, erichaagdev commented on modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
> +            remoteInputSpec.ifNotEmpty {value ->
I feel we should [log a warning](https://docs.gradle.org/current/userguide/logging.html) if both `inputSpec` and `remoteInputSpec` are set. It should mention that `remoteInputSpec` takes priority over `inputSpec`.

2022-10-29 13:22 UTC, erichaagdev commented on modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
> +            remoteInputSpec.ifNotEmpty {value ->
```suggestion
            remoteInputSpec.ifNotEmpty { value ->
```

2022-10-29 13:22 UTC, erichaagdev commented on modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
> +                "/modules/openapi-generator-gradle-plugin/src/test/resources/specs/petstore-v3.0.yaml"
I think it's okay for this URL to be all on one line.

```suggestion
        val specUrl = "https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator-gradle-plugin/src/test/resources/specs/petstore-v3.0.yaml"
```

2022-10-29 13:22 UTC, erichaagdev commented on modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
> +        val specUrl = "https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master" +
It might be a good idea to ping this to a specific commit or tag. That way changes to the remote spec won't affect the outcome of the test.

2022-10-29 17:31 UTC, erichaagdev commented
Could you also update [the configuration section of the README](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin#openapigenerate) to mention the new property?

2022-11-05 16:01 UTC, erichaagdev approved these changes
I think this looks good, but I don't have approval to merge.

2022-11-07 15:32 UTC, wing328 commented
@hdani9307 thanks for the PR.

@erichaagdev thanks for reviewing the change.

2022-11-07 15:32 UTC, merged