[java-spring] Move JsonProperty annotation from field to getter
OpenAPITools/openapi-generator pull request #13781
Opened 2022-10-20 14:42 UTC by ceremo

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### Description of the PR
Addresses https://github.com/OpenAPITools/openapi-generator/issues/5705 for Java Spring.

Technical commitee:
@cachescrubber @welshm @MelleD @atextor @manedev79 @javisst @borsch @Zomzog

2022-10-20 18:10 UTC, welshm commented on modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
> +  @JsonProperty("{{baseName}}")
This will need a `{{#jackson}}` check

2022-10-20 18:10 UTC, welshm commented on modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
>    {{#withXml}}
You may want some unit tests that validate where this property is being written - see something like `shouldGenerateDiscriminatorFromAllOfWhenUsingLegacyDiscriminatorBehaviour_issue12692`

2022-10-27 18:23 UTC, welshm approved these changes

2022-10-28 06:44 UTC, borsch approved these changes

2022-10-28 07:26 UTC, cachescrubber requested changes
Please move the the annotation directly over the getter method. Otherwise looks good.

2022-10-28 07:26 UTC, cachescrubber commented on modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
> +  @JsonProperty("{{baseName}}")
Can we move the `@JsonProperty` directly above the getter method? This would avoid empty lines in the generated model classes.

2022-10-28 07:26 UTC, cachescrubber commented on samples/client/petstore/spring-cloud-async/src/main/java/org/openapitools/model/Category.java
See comment above.

2022-10-28 14:36 UTC, wing328 commented
@ceremo thanks for the PR. Can you please resolve the merge conflicts when you've time?

2023-01-31 09:12 UTC, ceremo commented
Hi @wing328, conflicts fixed, could be included in the 6.3.0 version?

2023-02-09 14:45 UTC, jorgerod commented
@wing328  Could this PR be merged already?

2023-03-19 11:31 UTC, borsch commented
I've update this PR. Once pipelines are green, I'll merge this PR

2023-03-19 11:59 UTC, merged

2023-03-20 08:14 UTC, ceremo commented
> I've update this PR. Once pipelines are green, I'll merge this PR

Thxs @borsch.