[tyescript-axios] fix description for config options: withSeparateModelsAndAp, modelPackage, apiPackage
OpenAPITools/openapi-generator pull request #14103
Opened 2022-11-23 14:40 UTC by Lazzaretti

describe withSeparateModelsAndApi, modelPackage, apiPackage as mentioned in #5008

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

2022-11-23 16:47 UTC, macjohnny requested changes
please change the descriptions in https://github.com/OpenAPITools/openapi-generator/blob/3eb90a69e637bd7bf00bcc76aec72716f5ea2b54/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java#L62-L68 and then re-generate the docs by running 

```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```

2022-11-30 13:18 UTC, macjohnny approved these changes

2022-11-30 13:19 UTC, macjohnny commented on docs/generators/typescript-axios.md
> +|withSeparateModelsAndApi|Put the model and api in separate folders and in separate classes; this requires in addition a value for 'apiPackage' and 'modelPackage'| |false|
```suggestion
|withSeparateModelsAndApi|Put the model and api in separate folders and in separate classes. This requires in addition a value for 'apiPackage' and 'modelPackage'| |false|
```

2022-11-30 15:46 UTC, Lazzaretti commented
@macjohnny, do you know the node1 ci is failing? it does not seem related to that change.

2022-12-01 07:05 UTC, merged