Fix issue 12341
OpenAPITools/openapi-generator pull request #15234
Opened 2023-04-16 17:29 UTC by rodrigoma3

if method return type is void then no return.
Unit tests to verify that the API methods were created as expected.
fix #12341 
First commit has the changes made to fix the issue

### PR checklist
 
- [ X ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ X ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ X ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [ X ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ X ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09)

2023-04-17 07:31 UTC, borsch requested changes

2023-04-17 07:31 UTC, borsch commented on modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/MethodAssert.java
> +                "Method's %s body should contains lines\n====\n%s\n====\nbut actually was\n====\n%s\n====",
`should` -> `shouldn't`

2023-04-17 07:31 UTC, borsch commented on docs/generators/fsharp-functions.md
> +|sourceFolder|source folder for generated code| |OpenAPI\src|
re-generate all samples under unix/docker/WSL to fix these changes

2023-04-17 07:31 UTC, borsch commented on modules/openapi-generator-core/pom.xml
> +    <version>6.6.0</version>
pull latest master

2023-04-17 13:43 UTC, rodrigoma3 commented
@borsch resolved, could you look again and signal me if it's ok now please?

2023-04-18 14:01 UTC, borsch commented on samples/client/echo_api/python-nextgen/README.md
> +*BodyApi* | [**test_binary_gif**](docs\BodyApi.md#test_binary_gif) | **POST** /binary/gif | Test binary (gif) response body
doesn't seems like you have fixed this

2023-04-18 17:06 UTC, borsch requested changes

2023-04-18 17:06 UTC, borsch commented on samples/openapi3/server/petstore/springboot-delegate/src/main/java/org/openapitools/api/FakeApi.java
> +            getDelegate().createXmlItem(xmlItem);
doesn't seems to be correct

2023-04-18 17:06 UTC, borsch commented on modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
> +            {{^isVoid}}return {{/isVoid}}{{#isVoid}}{{#useResponseEntity}}return {{/useResponseEntity}}{{^useResponseEntity}}{{#reactive}}return {{/reactive}}{{/useResponseEntity}}{{/isVoid}}{{operat
remove spaces before `{{^isVoid}}`

2023-04-18 17:06 UTC, borsch commented on modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
> +            {{^isVoid}}return {{/isVoid}}getDelegate().{{operationId}}({{#allParams}}{{paramName}}{{^-last}}, {{/-last}}{{/allParams}}{{#reactive}}{{#hasParams}}, {{/hasParams}}exchange{{/reactive}}{
remove spaces before `{{^isVoid}}`

2023-04-18 19:16 UTC, rodrigoma3 commented
@borsch Sorry, something happened here and it messed up a lot. I fixed it and it looks right now. Thanks

2023-04-18 20:45 UTC, borsch approved these changes

2023-04-18 20:56 UTC, merged