Fix #17472 Do not generate validation for response
OpenAPITools/openapi-generator pull request #17730
Opened 2024-01-28 20:24 UTC by jpfinne

Since [4947] [java]: adds support for validation of primitives in arrays, the generated java code can be uncompilable. 

 See 
[BUG] generated code cannot be compiled (Java 21) #17472
[BUG][SPRING] Webflux minItems generates incompatible validation annotation #17564

The issue is in the regex in 
postProcessResponseWithProperty()
property.dataType = property.dataType.replaceAll("(?:(?i)@[a-z0-9, =()]*+\\s*)*+", "");

The regex only strips simple `@Valid` but fails with `@Size(min=10)`

This pull request takes a different approach.  It does not generate the bean validation for response so there is not need to clean the response in the post processor.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the 7.3.0
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@wing328 you did extensive review on the code of @Aliaksie.  
Can you review this pull request?

@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg (2023/08)
Please review

2024-01-29 05:19 UTC, wing328 commented
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

2024-01-29 06:46 UTC, MelleD commented
A test would be great

2024-01-29 08:46 UTC, jpfinne commented
@MelleD  Test added.
@wing328  GitHub account set (I hope so)

2024-01-29 11:58 UTC, MelleD commented
@jpfinne Thanks for the tests :).

I think a few more test cases are necessary for good coverage. Take a look at the other BeanValidation test, maybe you can expand that too. There are a lot of combinations.

e.g.
- what happens to a Set
- What happens if the list has a Dto class
- What about other validations regex etc.

2024-01-29 14:07 UTC, jpfinne commented
@MelleD a bit overkill when knowing the implementation.
But let's imagine we want blackbox testing, it it can speed up the merge...

I've tested your 3 uses cases:

- what happens to a Set
- What happens if the list has a Dto class
- What about other validations regex etc.

ps: There is no space between `@Valid `and `Size `in the generated `@Valid@Size(min = 5) `.  This is valid java code!
Something already present in 7.1.0
I've added JavaFileAssert.fileContainsPattern so that the test stays valid for `@Valid@Size(min = 5) ` and for `@Valid @Size(min = 5) `.

2024-02-02 15:17 UTC, martin-mfg requested changes

2024-02-02 16:21 UTC, jpfinne commented on modules/openapi-generator/src/test/resources/bugs/issue_17472.yaml
@martin-mfg Thanks for review.
Indeed the contract was corrupted.

2024-02-02 16:22 UTC, jpfinne commented
@martin-mfg The contract is updated

2024-02-02 17:53 UTC, MelleD commented
> a bit overkill when knowing the implementation.

Why? There is already a test and file with some combination etc.
Why you don’t reuse it?

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/bugs/issue_4947.yaml

2024-02-12 09:00 UTC, martin-mfg approved these changes

2024-03-13 07:03 UTC, wing328 commented
can you please resolve the merge conflicts when you've time?

2024-09-02 09:03 UTC, wing328 commented
closed via https://github.com/OpenAPITools/openapi-generator/pull/19093

2024-09-02 09:03 UTC, closed without merging