bugfix-20188: [JAVA][BUG] Do not use valueOf for numeric types for generating inner enums
OpenAPITools/openapi-generator pull request #20293
Opened 2024-12-11 13:19 UTC by timon-sbr

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### Technical Comittee
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

### Description
The template file `src/main/resources/Java/modelInnerEnum.mustache` was using the `valueOf()` method to create instances for enum fields. This does not work for every Object, because `valueOf()` is not implemented in every possible Object. `BigDecimal` for example does not provide the `valueOf(BigDecimal)` method. This behaviour results in invalid code through generation.
To fix this, I decided to only use the `valueOf` method, for non numeric types. It seems the decision to use the `valueOf` method was, to fix a bug for Boolean values (see: [PR-19815](https://github.com/OpenAPITools/openapi-generator/pull/19815/files) ). So this fix should be non breaking.

2024-12-15 08:45 UTC, wing328 commented
@timon-sbr thanks for the PR. 

Can you please add a test case or 2 in `modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml` and then regenerate the samples?

2024-12-17 08:39 UTC, timon-sbr commented
@wing328 thanks for the review. I've added some test data to `modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml` and regenerated the samples. Can you please check, if this is enough? I'm not sure, if I've also have to add java code to test the behaviour.

2024-12-30 07:21 UTC, wing328 commented
i did a test with https://raw.githubusercontent.com/OpenAPITools/openapi-generator/a8d3e7da44e268d32818e6d02d0a111d58f7bbea/modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml using the latest master CLI JAR but the output compiles without issue

is my understanding correct that the test spec (with the newly added test cases you just added) should generate output with compilation errors as described in the issue?

2025-01-03 13:03 UTC, timon-sbr commented
Hi @wing328 the Test Spec I've added tests the bugfix, so the output should generate a valid result, which is the fix of the issue.

2025-01-03 14:09 UTC, wing328 commented
In the issue, you mentioned

> The generated Code produces compiler errors, because it tries to create instances of BigDecimal with

but I couldn't repeat the compilation errors using the test spec you updated in this PR: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/a8d3e7da44e268d32818e6d02d0a111d58f7bbea/modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml

in other words, how did you produce the compilation errors?

2025-01-15 11:38 UTC, timon-sbr commented
Hi @wing328  sorry for the late response, I was in vacation. 
You can reproduce the issue if you run the samples generation at master with the updated spec:
https://[raw.githubusercontent.com/OpenAPITools/openapi-generator/a8d3e7da44e268d32818e6d02d0a111d58f7bbea/modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml](https://raw.githubusercontent.com/OpenAPITools/openapi-generator/a8d3e7da44e268d32818e6d02d0a111d58f7bbea/modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml)

One important note: You also have to use jersey als library to create the error (bin/configs/java-okhttp-gson.yaml):
```yaml
generatorName: java
outputDir: samples/client/petstore/java/okhttp-gson
library: okhttp-gson
inputSpec: modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
nameMappings:
  _type: underscoreType
  type_: typeWithUnderscore
parameterNameMappings:
  _type: underscoreType
  type_: typeWithUnderscore
additionalProperties:
  artifactId: petstore-okhttp-gson
  hideGenerationTimestamp: true
  useOneOfDiscriminatorLookup: true
  disallowAdditionalPropertiesIfNotPresent: false
  useReflectionEqualsHashCode:: true
  library: resteasy #This line is important to reproduce the error
enumNameMappings:
  s: LOWER_CASE_S
  S: UPPER_CASE_S
operationIdNameMappings:
  getArrayOfEnums: getFakeArrayofenums
  fakeHealthGet: getFakeHealth
```

2025-01-29 18:55 UTC, martin-mfg commented
Hi @timon-sbr, thanks for the PR!

After reviewing your changes I extended them a bit. You can find the extended version, consisting of your commits and my commits here: https://github.com/martin-mfg/openapi-generator/pull/63

I assume that you want to see a successfully completed PR to OpenAPI Generator on your Github profile. Therefore I didn't open a competing PR of our combined changes to OpenAPI Generator. Instead, you can include my changes into your branch by merging [this](https://github.com/timon-sbr/openapi-generator/pull/1). I will then approve your PR here and it can get merged and you get the credit. :)

**What did I change on top of your changes?**
- applied your fix to more Java libraries
- fixed a problem in your yaml changes ("double" is not a valid type, but "number" is)
- copied your yaml changes to an additional test input file, thereby fulfilling @wing328's requested discussed in the comments above
- removed one of the yaml changes in each of the two changed yaml files, because they triggered bugs in some sample configurations. Those bugs are not related to the problem fixed in this PR.
- merged master branch to resolve a merge conflict

2025-01-29 18:56 UTC, martin-mfg requested changes
Hi @timon-sbr, thanks for the PR!

After reviewing your changes I extended them a bit. You can find the extended version, consisting of your commits and my commits here: https://github.com/martin-mfg/openapi-generator/pull/63

I assume that you want to see a successfully completed PR to OpenAPI Generator on your Github profile. Therefore I didn't open a competing PR of our combined changes to OpenAPI Generator. Instead, you can include my changes into your branch by merging [this](https://github.com/timon-sbr/openapi-generator/pull/1). I will then approve your PR here and it can get merged and you get the credit. :)

**What did I change on top of your changes?**
- applied your fix to more Java libraries
- fixed a problem in your yaml changes ("double" is not a valid type, but "number" is)
- copied your yaml changes to an additional test input file, thereby fulfilling @wing328's requested discussed in the comments above
- removed one of the yaml changes in each of the two changed yaml files, because they triggered bugs in some sample configurations. Those bugs are not related to the problem fixed in this PR.
- merged master branch to resolve a merge conflict

2025-01-30 13:03 UTC, timon-sbr commented
Hi @martin-mfg thank you very much for the explanation and extending this bugfix to other libraries. I've merged your changes right now :)

2025-01-30 13:40 UTC, martin-mfg approved these changes

2025-03-12 14:45 UTC, timon-sbr commented
Any Chances This PR get's merged @martin-mfg ?

2025-03-12 16:36 UTC, martin-mfg commented
I don't have merge privileges here, so we need to wait for a project maintainer to merge your PR. In the meantime it would be great if you could resolve the merge conflicts.

2025-03-13 15:01 UTC, wing328 commented
looks like a rebase failed and therefore this PR includes commits from others.

can you please file a new one based on the latest master?

2025-04-08 15:09 UTC, timon-sbr commented
Hi @wing328 I've created a new PR based on the current master:
https://github.com/OpenAPITools/openapi-generator/pull/21055

I will close this PR.

2025-04-08 15:09 UTC, closed without merging