[WIP][csharp-netcore] Add "httpclient" library support
OpenAPITools/openapi-generator pull request #8331
Opened 2021-01-05 07:56 UTC by wing328

Add support for HttpClient library

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

2021-01-05 22:06 UTC, devhl-labs commented
So I should carry on with what I was doing and later do pr's to your new branch of csharp-netcore-httpclient? The files at `/csharp-netcore-httpclient/modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient` are those the only files that I can be library specific, or can I just add the templates that are not present yet?

2021-01-06 02:49 UTC, wing328 commented
@devhl-labs yes please work on the `csharp-netcore-httpclient` branch.

> are those the only files that I can be library specific, or can I just add the templates that are not present yet?

Feel free to add more. Those are the one I found in your PRs. If the generator cannot find the mustache templates in `modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient`, it will use the default in `modules/openapi-generator/src/main/resources/csharp-netcore/`

2021-01-06 03:20 UTC, wing328 commented on modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/api.mustache
> +        ApiResponse<{{#returnType}}{{{returnType}}}{{/returnType}}{{^returnType}}Object{{/returnType}}> {{operationId}}Response({{#allParams}}{{{dataType}}} {{paramName}}{{^required}}{{#optionalMetho
@devhl-labs I noticed that you've renamed `WithHttpInfo` with `Response`. I'm not against a different naming for methods that return HTTP headers, status code, etc but if the method name already ends with `response`, the method name may end up like `getResponseResponse`.

We may need to add an option to customize this instead.

2021-01-06 03:29 UTC, wing328 commented
@devhl-labs for other generators (e..g Java, Ruby), we only updated the ApiClient.mustache file with a different Http library most of the time (In other words, the ApiClient is swappable with a different implementation of HTTP library). For other templates (e.g. csproj files that list out the dependencies), we can use `{{#isHttpClient}} ... {{/isHttpClient}}` mustache tag instead to avoid maintaining too many customized files under `modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient`

2021-01-08 02:28 UTC, wing328 commented
@devhl-labs when you've time, can you please PM me via Slack to have quick chat on this?

https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

2021-02-06 14:21 UTC, devhl-labs commented
@wing328 can you merge this and also 8465? There is still work to be done but im not doing it all, so might as well release it with partial support.

2021-02-22 18:06 UTC, Blackclaws commented
Just tested it out. 

Found a weird reference to CocApi in the generated Client which seems superfluous.

Also it uses a couple of C#9 language features which makes the generated output unnecessarily incompatible with netstandard 2.1. It should at least allow a fallback to that, as one of the requested and one of our usecases as well is usage of generated code within Unity which is incompatible with Net 5.0.

If you want I can open a pullrequest with changes on this branch. Let me know!

2021-02-24 18:55 UTC, devhl-labs commented
I'll remove the unrelated api reference. I think the only C# 8 feature you're referring to is the nullable reference types, which we can fix with a small change to the post processing powershell.

How can I create only samples for my library so I don't have conflicts with unrelated libraries? I currently see a conflict with typescript which I did not touch.

2021-02-25 10:16 UTC, Blackclaws requested changes
I noted a couple of the issues that directly pop up when you change to netstandard and c# 8.

If you also go below C#8 you of course run into the nullable reference type issue.

The ??? mark issue is also present without changing to netstandard.

In general I think this might be better suited as a separate generator instead of a library for the normal csharp-netcore generator as it is quite a change from what the restsharp version is producing.

2021-02-25 10:16 UTC, Blackclaws commented on modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/api.mustache
> +            ApiResponse<{{#returnType}}{{{returnType}}}{{/returnType}}{{^returnType}}Object{{/returnType}}> apiResponse = new(responseMessage, responseContent);
This is C# 9 syntax.

2021-02-25 10:16 UTC, Blackclaws commented on modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/netcore_project.mustache
> +    <!--<PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />-->
This reference is needed for netstandard

2021-02-25 10:16 UTC, Blackclaws commented on modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/netcore_project.mustache
> +    <!--<TargetFramework>{{targetFramework}}</TargetFramework>--><TargetFramework>net5.0</TargetFramework>
Target Framework should not be hardcoded

2021-02-25 10:16 UTC, Blackclaws commented on modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/api.mustache
> +        System.Threading.Tasks.Task<ApiResponse<{{#returnType}}{{{returnType}}}{{/returnType}}{{^returnType}}Object{{/returnType}}>> {{operationId}}WithHttpInfoAsync({{#allParams}}{{#required}}{{{dat
What are the ??? supposed to do? I think there are two superfluous ?. This is throwing errors for me at least

2021-02-25 13:53 UTC, devhl-labs commented
The ??? is a placeholder. It gets fixed in the post processing. Check the readme file to see a powershell script that both runs the jar and then executes the fix. The issue is that a reference type is declared by Type not Type? so i need some placeholder to mark the object as nullable.

2021-02-25 14:06 UTC, Blackclaws commented
> The ??? is a placeholder. It gets fixed in the post processing. Check the readme file to see a powershell script that both runs the jar and then executes the fix. The issue is that a reference type is declared by Type not Type? so i need some placeholder to mark the object as nullable.

Which Readme? Its not in the generated Readme.md. I think if there is post processing required especially via a tool like powershell I'm leaning more and more towards this being a separate generator. Powershell Core is included in current dotnet/sdk docker images so it might not be an issue for people using that in their pipeline, that might not be everyone though. I'd specifically mention that as a requirement and maybe even check whether the postprocessing couldn't be done within the generator itself if it is needed.

2021-02-25 18:57 UTC, devhl-labs commented
It's here at the top:

<https://github.com/devhl-labs/openapi-generator/tree/csharp-netcore-httpclient/modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient>

What does a generator mean to you? We seem to have different definitions. I've already suggested in the slack channel that we restructure the csharp folders like below.  We have a bunch of csharp folders and it's very confusing which to use. Even one aspnet generator which you may not even see if you go looking for csharp options.

```
csharp
  client
    libraries(http, restsharp, etc)
      version
  server
    libraries(http, restsharp, etc)
      version
```

2021-02-26 08:21 UTC, Blackclaws commented
We might indeed have different definitions. Let me try to give mine:

A generator has a specific feature set that allows me to fine tune the output and supports a specific language. I expect a generator to be as compatible as possible between versions as I have code depending on the output.

It might also have to do with how we use generators in our workflow. We don't create a server implementation, export the openapi spec, then generate a client and just keep modifying that. We build the openapi spec and then create abstract server base classes and automatic client libraries via generation, those also aren't committed but are regenerated on CI runs, hence why we kind of rely on the fact that they don't break the exposed API surface on upgrading the generator (we could just stick to one version of the generator, but that also keeps us from getting bug fixes). 

I think your restructuring is indeed a good idea when we talk about the template folders. I don't think its possible at least not easily to merge the generator classes into one. That is due to the fact that the tasks they perform might be very different and they expose different command line switches. Having a switch that pertains to the server implementation exposed on the client generator is confusing.

2021-06-10 12:57 UTC, lucamazzanti commented
Is this still useful? Unfortunately it seems to have gone in a different direction since the latest changes.
Probably if there are contributions it could be useful to redo the PR from the current master and apply just the mustache parts.
Otherwise it can be closed.

2021-06-10 13:01 UTC, devhl-labs commented
Ill be working on this this weekend.

2022-01-03 09:11 UTC, closed without merging