Fix #8027 - don't import JSON class if generateSupportingFiles is false
OpenAPITools/openapi-generator pull request #8554
Opened 2021-01-27 16:54 UTC by MosheElisha

Import the auto generated supporting JSON class only when generateSupportingFiles is true.

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

2021-01-28 10:00 UTC, MosheElisha commented
@bgong-mdsol @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch mentioning the technical committee as requested and the last modifier of the template file. Please review. Thanks in advance.

2021-02-02 23:02 UTC, Zomzog commented
The import looks unused for the simple models so it may be just removed.
But not il all_of where it is used. So even with `generateSupportingFiles=true` it must be added.

2021-02-02 23:09 UTC, MosheElisha commented
Thanks, @Zomzog . If `generateSupportingFiles=false`, we can surely remove the import otherwise it won't compile, right?

If so, isn't removing the `import ...JSON` when `generateSupportingFiles=false` is simpler?

If `JSON` is used and `generateSupportingFiles=false` you will have a compilation issue and you will understand you need to change `generateSupportingFiles` to `true`.

2021-02-03 03:23 UTC, wing328 commented
cc @OpenAPITools/generator-core-team

2021-02-03 06:09 UTC, Zomzog commented
> Thanks, @Zomzog . If `generateSupportingFiles=false`, we can surely remove the import otherwise it won't compile, right?
> 
> If so, isn't removing the `import ...JSON` when `generateSupportingFiles=false` is simpler?
> 
> If `JSON` is used and `generateSupportingFiles=false` you will have a compilation issue and you will understand you need to change `generateSupportingFiles` to `true`.

What I think is you can just remove it from the model.mustache without any condition.
But in other model templates like the anyof the import is used so you must keep it. If the user make the choice of skipping generateSupportingFiles he must provide JSON class in another way.

2021-02-03 07:54 UTC, MosheElisha commented
@Zomzog OK. Thanks for the review! I'll remove the `import ...JSON` from `model.mustache` all together.

2021-02-03 09:43 UTC, MosheElisha commented
@Zomzog `continuous-integration/drone/pr` job failed. Seems `JSON` is used in model classes sometimes.

```
/drone/src/samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/Dog.java:[118,3] cannot find symbol
[ERROR]   symbol:   variable JSON
[ERROR]   location: class org.openapitools.client.model.Dog
```

For example, `openapi-generator/samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/Dog.java`:

```
public class Dog extends Animal {
...
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("Dog", Dog.class);
  JSON.registerDiscriminator(Dog.class, "className", mappings);
}
}
```

2021-02-04 21:03 UTC, Zomzog commented
Ok, in this case maybe the import condition may be done like 
```
{{#model}}
{{#discriminator}}
import {{invokerPackage}}.JSON;
{{/discriminator}}
```
I'm not sure it's really useful to try to remove this import because most of the supporting files must be generated or provided in one way or another. Does this one really create an issue in particular cases?

2021-02-04 22:38 UTC, MosheElisha commented
Thanks, @Zomzog . That is a good observation. There is a `generateSupportingFiles` and you assume that it should be possible to make it false but as it turns out it the "supporting files" are mandatory in this case.

I'm guessing one approach is to make the supporting files list as minimal as possible. For example:

```
<supportingFilesToGenerate>JSON.java,RFC3339DateFormat.java</supportingFilesToGenerate>
```

In my case, I don't want and don't need the supporting files. I just want to generate model classes as POJOs.
The problem I have is that these two supporting files also require me to add dependencies on `jackson-datatype-jsr310`, `jackson-databind-nullable` and `jakarta.ws.rs-api`.

In my case, my auto generated model classes are not using the JSON class at all so I don't need the supporting files and all the dependencies. I want to be able to share and use the "model classes" in other use cases (e.g., sending them in a queue) and I want the receiving end to be able to depend on the "model classes" jar without too many unnecessary dependencies.

I will try your suggestion with the `discriminator` flag.

2021-02-05 17:08 UTC, MosheElisha commented
@wing328 @Zomzog I believe `Shippable` failure is unrelated to my changes can you please verify/rerun and review if PR is OK?

I tested `discriminator` flag in the `pojo.mustache` as it is undefined in the `model.mustache`.

Thanks.

2021-02-10 20:47 UTC, Zomzog requested changes

2021-02-10 20:47 UTC, Zomzog commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
> +        config.additionalProperties().put("generateSupportingFiles", generateSupportingFiles);
I think you can remove this line.

2021-02-10 21:41 UTC, MosheElisha commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
> +        config.additionalProperties().put("generateSupportingFiles", generateSupportingFiles);
Indeed. Done.

2021-02-12 15:02 UTC, wing328 commented
Tested locally and no issue found.

I found some warnings though:
```
[WARNING] Javadoc Warnings
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/JSON.java:63: warning: no @return
[WARNING] public static Class<?> getClassForElement(JsonNode node, Class<?> modelClass) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/JSON.java:168: warning: no @param for visitedClasses
[WARNING] public static boolean isInstanceOf(Class<?> modelClass, Object inst, Set<Class<?>> visitedClasses) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/JSON.java:168: warning: no @return
[WARNING] public static boolean isInstanceOf(Class<?> modelClass, Object inst, Set<Class<?>> visitedClasses) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:84: warning: no @return
[WARNING] public CompletableFuture<Void> createXmlItem(XmlItem xmlItem) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:519: warning: no @return
[WARNING] public CompletableFuture<Void> testBodyWithFileSchema(FileSchemaTestClass body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:599: warning: no @return
[WARNING] public CompletableFuture<Void> testBodyWithQueryParams(String query, User body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:798: warning: no @return
[WARNING] public CompletableFuture<Void> testEndpointParameters(BigDecimal number, Double _double, String patternWithoutDelimiter, byte[] _byte, Integer integer, Integer int32, Long int64, Float _float, String string, File binary, LocalDate date, OffsetDateTime dateTime, String password, String paramCallback) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:903: warning: no @return
[WARNING] public CompletableFuture<Void> testEnumParameters(List<String> enumHeaderStringArray, String enumHeaderString, List<String> enumQueryStringArray, String enumQueryString, Integer enumQueryInteger, Double enumQueryDouble, List<String> enumFormStringArray, String enumFormString) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:997: warning: no @return
[WARNING] public CompletableFuture<Void> testGroupParameters(APItestGroupParametersRequest apiRequest) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:1035: warning: no @return
[WARNING] public CompletableFuture<Void> testGroupParameters(Integer requiredStringGroup, Boolean requiredBooleanGroup, Long requiredInt64Group, Integer stringGroup, Boolean booleanGroup, Long int64Group) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:1216: warning: no @return
[WARNING] public CompletableFuture<Void> testInlineAdditionalProperties(Map<String, String> param) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:1296: warning: no @return
[WARNING] public CompletableFuture<Void> testJsonFormData(String param, String param2) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:1378: warning: no @return
[WARNING] public CompletableFuture<Void> testQueryParameterCollectionFormat(List<String> pipe, List<String> ioutil, List<String> http, List<String> url, List<String> context) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:79: warning: no @return
[WARNING] public CompletableFuture<Void> addPet(Pet body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:159: warning: no @return
[WARNING] public CompletableFuture<Void> deletePet(Long petId, String apiKey) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:521: warning: no @return
[WARNING] public CompletableFuture<Void> updatePet(Pet body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:602: warning: no @return
[WARNING] public CompletableFuture<Void> updatePetWithForm(Long petId, String name, String status) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java:76: warning: no @return
[WARNING] public CompletableFuture<Void> deleteOrder(String orderId) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:76: warning: no @return
[WARNING] public CompletableFuture<Void> createUser(User body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:155: warning: no @return
[WARNING] public CompletableFuture<Void> createUsersWithArrayInput(List<User> body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:234: warning: no @return
[WARNING] public CompletableFuture<Void> createUsersWithListInput(List<User> body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:313: warning: no @return
[WARNING] public CompletableFuture<Void> deleteUser(String username) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:577: warning: no @return
[WARNING] public CompletableFuture<Void> logoutUser() throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:646: warning: no @return
[WARNING] public CompletableFuture<Void> updateUser(String username, User body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java:83: warning: no @param for key
[WARNING] public AdditionalPropertiesAnyType putAdditionalProperty(String key, Object value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java:83: warning: no @param for value
[WARNING] public Additio [...]

2021-02-12 15:02 UTC, merged

2021-02-12 22:21 UTC, MosheElisha commented
Thank you @wing328 and @Zomzog for reviewing!

2021-03-22 06:24 UTC, wing328 commented
@MosheElisha thanks for the PR, which has been included in the v5.1.0 release: https://twitter.com/oas_generator/status/1373636654024380423