Generate TypeScript Docs and Examples
OpenAPITools/openapi-generator pull request #9413
Opened 2021-05-05 22:44 UTC by NouemanKHAL

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

2021-05-06 09:31 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +        return "new Date('" + strValue + "')";
Make sure that this is necessary for typescript.

2021-05-06 09:31 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +    private String toExampleValueRecursive(String modelName, Schema schema, Object objExample, int indentationLevel, String prefix, Integer exampleLine, Set<Schema> seenSchemas) {
I don't think modelName is necessary anymore.

2021-05-06 09:31 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +    public String toExampleValue(Schema schema) {
You should call the method below once you have the example value.

2021-05-06 09:31 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +        if (ModelUtils.isStringSchema(sc) && !ModelUtils.isDateSchema(sc) && !ModelUtils.isDateTimeSchema(sc) && !"Number".equalsIgnoreCase(sc.getFormat()) && !ModelUtils.isByteArraySchema(sc) && !Mo
```suggestion
        return (ModelUtils.isStringSchema(sc) && !ModelUtils.isDateSchema(sc) && !ModelUtils.isDateTimeSchema(sc) && !"Number".equalsIgnoreCase(sc.getFormat()) && !ModelUtils.isByteArraySchema(sc) && !ModelUtils.isBinarySchema(sc) && schema.getPattern() == null)
```

2021-05-06 09:31 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +                    String chosenModelName = mm.getModelName();
Both lines look unused.

2021-05-06 09:31 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +            return fullPrefix + "None" + closeChars;
Looks wrong to me.

2021-05-06 09:31 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +                example = "True";
Same here.

2021-05-06 09:31 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +            example = "new " + "{{moduleName}}" + "." + type + "()";
Maybe need fixing.

2021-05-06 09:31 UTC, therve commented on samples/openapi3/client/petstore/typescript/builds/object_params/PetApi.md
> +import  from '';
Looks like it's missing projectName here.

2021-05-06 09:31 UTC, therve commented on samples/openapi3/client/petstore/typescript/builds/object_params/PetApi.md
> +const apiInstance = new .PetApi();
Missing moduleName here.

2021-05-06 09:31 UTC, therve commented on samples/openapi3/client/petstore/typescript/builds/default/PetApi.md
> +let opts = {
Needs to pass them one by one instead.

2021-05-06 09:31 UTC, therve commented on samples/openapi3/client/petstore/typescript/builds/default/PetApi.md
> + **tags** | [**Array&lt;string&gt;**](string.md)| Tags to filter by | defaults to undefined
string.md probably doesn't exist, need to check for basic types.

2021-05-06 09:31 UTC, therve commented on samples/openapi3/client/petstore/typescript/builds/default/PetApi.md
> +    ]; // Array<string> | Tags to filter by
Here you probably want to change indentation strategy.

2021-05-06 09:31 UTC, therve commented on samples/openapi3/client/petstore/typescript/builds/default/PetApi.md
> +            id:1,
Add a space after the colon.

2021-05-06 09:31 UTC, therve commented on samples/openapi3/client/petstore/typescript/builds/default/PetApi.md
> + **file** | [**HttpFile**](File.md)| file to upload | [optional] if omitted the server will use the default value of undefined
Same File.md doesn't exist.

2021-05-11 07:58 UTC, therve requested changes
Looks good, some minor improvements.

2021-05-11 07:58 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +        return toExampleValueRecursive(modelName, schema, objExample, 1, "", 0, Sets.newHashSet());
```suggestion
        return toExampleValueRecursive(modelName, schema, objExample, 0, "", 0, Sets.newHashSet());
```

2021-05-11 07:58 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +        final String indentionConst = "    ";
```suggestion
        final String indentionConst = "  ";
```

2021-05-11 07:58 UTC, therve commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
> +     *                         we assume the indentaion amount is 4 spaces times this integer
```suggestion
     *                         we assume the indentaion amount is 2 spaces times this integer
```

2021-05-11 07:58 UTC, therve commented on modules/openapi-generator/src/main/resources/typescript/api_doc.mustache
> +{{#requiredParams}}
You should remove this, and browse `allParams` instead.

2021-05-11 07:58 UTC, therve commented on modules/openapi-generator/src/main/resources/typescript/api_doc.mustache
> +{{#-first}}
You can remove the first as well I believe.

2021-05-11 07:58 UTC, therve commented on modules/openapi-generator/src/main/resources/typescript/api_doc.mustache
> +{{#hasParams}}
You can remove this.

2021-05-11 07:58 UTC, therve commented on modules/openapi-generator/src/main/resources/typescript/api_doc.mustache
> +{{#requiredParams}}{{^defaultValue}} **{{paramName}}** | {{^isPrimitiveType}}**{{{dataType}}}**{{/isPrimitiveType}}{{#isPrimitiveType}}[**{{dataType}}**]{{/isPrimitiveType}}| {{description}} |
Same here,  you should be aable to browse  `allParams` instead of doing required then optional.

2021-05-11 07:58 UTC, therve commented on modules/openapi-generator/src/main/resources/typescript/api_doc.mustache
> +{{^allParams}}This endpoint does not need any parameter.{{/allParams}}{{#allParams}}{{#-last}}
Use `hasParams` intead.

2021-05-11 08:18 UTC, therve commented on modules/openapi-generator/src/main/resources/typescript/api_doc.mustache
> +{{#requiredParams}}{{^defaultValue}} **{{paramName}}** | {{^isPrimitiveType}}**{{{dataType}}}**{{/isPrimitiveType}}{{#isPrimitiveType}}[**{{dataType}}**]{{/isPrimitiveType}}| {{description}} |
Need to remove the `[]` as well.

2021-05-11 08:18 UTC, therve commented on modules/openapi-generator/src/main/resources/typescript/api_doc.mustache
> +{{#returnType}}{{#returnTypeIsPrimitive}}**{{{returnType}}}**{{/returnTypeIsPrimitive}}{{^returnTypeIsPrimitive}}[**{{{returnType}}}**]{{/returnTypeIsPrimitive}}{{/returnType}}{{^returnType}}void (em
```suggestion
{{#returnType}}{{#returnTypeIsPrimitive}}**{{{returnType}}}**{{/returnTypeIsPrimitive}}{{^returnTypeIsPrimitive}}**{{{returnType}}}**{{/returnTypeIsPrimitive}}{{/returnType}}{{^returnType}}void (empty response body){{/returnType}}
```

2021-05-12 07:16 UTC, therve approved these changes

2021-05-12 12:51 UTC, NouemanKHAL commented
@TiFu @taxpon  @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov

2021-06-06 19:17 UTC, NouemanKHAL commented
I guess the CI is good now, can anyone take a look please?
@TiFu @taxpon  @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov

2021-06-12 07:30 UTC, TiFu approved these changes

2021-06-12 07:31 UTC, merged

2021-06-12 07:31 UTC, TiFu commented
Looks good to me - Circleci failure is unrelated.

Thank you for the PR!

2021-06-12 08:15 UTC, TiFu commented
@wing328 Could you please shed some light on the below? I am getting some workflow error that I can't really pin-point to this PR:
https://github.com/OpenAPITools/openapi-generator/runs/2808884555

```
1s
Run actions/download-artifact@v2.0.9
Starting download for artifact
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 1
Artifact artifact was downloaded to /home/runner/work/openapi-generator/openapi-generator
Artifact download has finished successfully
0s
Run git config --global core.fileMode false
  git config --global core.fileMode false
  git config --global core.safecrlf false
  git config --global core.autocrlf true
  mkdir -p modules/openapi-generator-cli/target/
  mv artifact/openapi-generator-cli.jar modules/openapi-generator-cli/target/
  ./bin/utils/ensure-up-to-date 
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
mv: cannot stat 'artifact/openapi-generator-cli.jar': No such file or directory```

2021-06-14 05:03 UTC, lwj5 commented
This broke something:

```
  Exception: null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1145)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1038)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:561)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:878)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.languages.TypeScriptClientCodegen.toExampleValueRecursive(TypeScriptClientCodegen.java:1230)
	at org.openapitools.codegen.languages.TypeScriptClientCodegen.toExampleValueRecursive(TypeScriptClientCodegen.java:1077)
	at org.openapitools.codegen.languages.TypeScriptClientCodegen.toExampleValue(TypeScriptClientCodegen.java:980)
	at org.openapitools.codegen.languages.TypeScriptClientCodegen.setParameterExampleValue(TypeScriptClientCodegen.java:1464)
	at org.openapitools.codegen.DefaultCodegen.fromRequestBody(DefaultCodegen.java:6238)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:3855)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1113)
	... 6 more
```

I'll try to distil down my YAML and post one that has issues. I cannot post the whole YAML as it's an internal document.

2021-06-14 05:35 UTC, TiFu commented
Many thanks! Let me revert this in the meantime.

2021-06-16 06:43 UTC, TiFu commented
@NouemanKHAL Could you please review and re-file (sorry!) with a fix for the spec that @lwj5 provided?